version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "myPassword"
    volumes:
      - ./data:/data/db
  adminer:
    image: adminer
    restart: always
    ports:
      - "8585:8585"